# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# OLED display
CONFIG_ZMK_DISPLAY=y

# Ext power (needed for EP_TOG/EP_ON/EP_OFF bindings in keymap)
CONFIG_ZMK_EXT_POWER=y
