# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# OLED display — shared settings for both halves
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Bluetooth + ext power
CONFIG_ZMK_EXT_POWER=y
